title: Site admin set-up
description: Need to learn for making my own website.
template:
  repo: site-admin-set-up-template
  name: site-admin-set-up
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
